### ISSUE TITLE
textmarker.highlightColors set to a single color option still uses two colors.

### ISSUE THREAD

**Issue by BouncingBison** [ryu1kn/vscode-text-marker#13]
When I specify this setting to use only one color (such as dark blue) the highlighter will be dark blue on the first item i highlight within a file. however when i highlight a second item instead of the dark blue that i have in my settings, i instead get a light gray highlight on all other items i choose in the file. If i remove all highlights within the file and begin highlighting again the problem will repeat itself. Ive included some screen shots to show the color selections in settings and in action within the files. 
<img width="271" alt="screen shot 2018-04-07 at 2 38 44 pm" src="https://user-images.githubusercontent.com/19629411/38459612-7b5c36d4-3a71-11e8-98ca-a3bd3d2ae4f6.png">
<img width="398" alt="screen shot 2018-04-07 at 2 29 41 pm" src="https://user-images.githubusercontent.com/19629411/38459601-4ff722d8-3a71-11e8-8ca9-c146a7bf1baa.png">
<img width="289" alt="screen shot 2018-04-07 at 2 31 27 pm" src="https://user-images.githubusercontent.com/19629411/38459602-50173654-3a71-11e8-9b50-bee1bf32a23b.png">

**Comment by ryu1kn** [comment]
Hi @BouncingBison , thanks for your comment with the clear description and screenshot. Screenshot always help me understand things quicker!

As for the behaviour you observed, it is actually meant to be that way, and there is a [test case](https://github.com/ryu1kn/vscode-text-marker/blob/b717373375c0833528a42310159d6fce4f8114f3/test/unit/colour-registry.test.js#L22) confirming it. Once it used all `highlightColors`, it starts using [`DEFAULT_COLOUR `](https://github.com/ryu1kn/vscode-text-marker/blob/f4f789f087fa7e9ccb59b22a0de3a8ac1861a728/lib/colour-registry.js#L2) (i.e. `gray`) for all the subsequent highlights, as it doesn't know what colours to use otherwise.

What we can do to avoid this confusion could be to mention this thing on the `textmarker.highlightColors`'s [description](https://github.com/ryu1kn/vscode-text-marker/blob/b717373375c0833528a42310159d6fce4f8114f3/package.json#L45). What do you think?

**Comment by BouncingBison** [comment]
I think that would be a great solution and gives people a great starting point!

**Comment by ryu1kn** [comment]
Cool @BouncingBison . Let me update the description then I'll close this ticket.

**Comment by ryu1kn** [comment]
Added the note, thank you! 👍
