### ISSUE TITLE
Highlight disappears when reopening html sheet

### ISSUE THREAD

**Issue by MEKKIHUSSEIN** [ryu1kn/vscode-text-marker#40]
Text highlighting disappears whenever I close and **reopen** any file.
(**I did save it** but the problem persists).

The GIF below shows the problem.
![2019-08-19-20-48_1](https://user-images.githubusercontent.com/24927440/63289748-86a94a00-c2c8-11e9-8258-198c9c7c3d27.gif)

**Comment by ryu1kn** [comment]
Hi @MEKKIHUSSEIN , thanks for the very helpful gif!

Since Text Marker doesn’t save highlights in your html file, saving with File menu “Save” won’t persist the highlights. Instead, you need to use **”Save All Highlights”** command of Text Marker. You can find it by start typing it into Code’s command pallete (Ctrl + Shift + P). Let me know if you see issues 👍
