### ISSUE TITLE
marker are not save ?

### ISSUE THREAD

**Issue by djmisterjon** [ryu1kn/vscode-text-marker#5]
> Ryuichi Inagaki
> 14 hours ago

**Happy New Year to you and thank you for your plugin.**
I'd like to use your plugin to improve my js codes in a game engine developer context.
I would like to know, if will be possible do similar highlight of what [_notepad++_] allowed.
Here is a rough example to highlight and separate some line of code. in [_notepad++_]
**Your plugin is ideal for me, but highlight does save when closed?**
[http://imgbox.com/ONUBaWcn](http://imgbox.com/ONUBaWcn)

I would like to be able to highlight with a white background color and saved. :)
I'm new to VBC and I love it, I only regret marker layout, but your plugin will seem able to offer this context
Thank you  friend

**Comment by ryu1kn** [comment]
Thanks for your suggestion. The image was very helpful 👍 

Let me first explain what are my main motivations for developing this extension. They are:

* Help me understand what's going on in the system by highlighting multiple keywords (like certain user id, ip address, ...) in log files (like access log, application log, ...)
* Help me be sure if system is correctly configured by highlighting multiple keywords through multiple source code or configuration files
* Help me understand which bit of code has reference to which variables while I read rather complex source code

Now, It seems like what you want to achieve is to always emphasise certain statements (like `console.log` debug statements) or comments that start with certain sequence (like `##`).

Adding the **save** functionality to the extension would be useful so that I can close the editor and resume the log reading later. Supporting regex to highlight would also be great. It allows me to highlight not only the texts beginning with `##` but also texts with slight variation such as date string. I'll think supporting it.

But perhaps, as what you want is more like customisation of your syntax highlighting, if you're only thinking about js, it might be faster if you write your own js syntax highlighting and replace the default one. cf. [Adding Language Colorization](https://code.visualstudio.com/Docs/customization/colorizer#_adding-a-new-language) 😉

**Comment by djmisterjon** [comment]
> comments that start with certain sequence (like ##).

> Adding the save functionality to the extension 

I was afraid, not to be understood but you seem to have all understood !!
for the Adding Language Colorization, 
I am an elder of (notepad ++).
At the moment I still find it super complicate the methods of custom syntax Colorization, .
But, I hope a pro like you, is able to help me with your plugin.
For now, I still find super complicating methods of personal syntax on VBC.
I will be very happy with your plugin, if we can highlight a few lines of code and save it.

Example: Key: _CTRL + H_ [for color], and _CTRL + ALT + H_ [to switch background color].

**Thank you very much friend, for your attention, I remain alert of your updates.
Your plugin is really helpfull for me .**
_If my request does not seem to use you.
It does not matter, I was simply suggestion hoping for a positive answer._

have nice day

**Comment by thomasf** [comment]
It would maybe be a good thing to be able to add highlights to user or workspace settings to manually persist some hl's.

**Comment by ryu1kn** [comment]
@thomasf Sorry, somehow I missed your comment...

Cool, seems we can use `WorkspaceConfiguration#update` introduced in code v1.6

**Comment by ryu1kn** [comment]
I use this issue for persisting highlights. Supporting regular expressions will be done in https://github.com/ryu1kn/vscode-text-marker/issues/8

**Comment by djmisterjon** [comment]
yes it work thank

**Comment by Otiel** [comment]
Any progress on the _save highlights_ functionality? Are you still considering adding it or has it been dropped?

**Comment by ryu1kn** [comment]
Not dropped. I think this feature is useful. I just haven't got enough time to work on this at the moment

**Comment by ryu1kn** [comment]
Things to consider

### On saving highlights
 
* Which settings (user/workspace) to save highlights to?
  a. Ask user which settings to save all highlights to
  a. Ask user which highlight to save to which settings
  a. Save to workspace settings
* Replace saved highlights or add highlights?
  * ➡️ Replace
* What if a highlight is already saved in user settings when saving into workspace settings?
  * Do not save into workspace settings
* What if a highlight is already saved in user settings and now it's toggled off and then *save to workspace settings* triggered?
  a. Leave the highlight in user settings
  a. Remove the highlight from user settings

### On restoring highlights

* When to restore highlights?
  a. On extension start
  b. On restore highlights command invocation
* How to read settings?
  a. Only read the most specific settings (workspace settings if it exists)
  b. Merge all settings (read both workspace and user settings), like `search.exclude` setting.
    * What if user doesn't want to inherit the user level highlights?

**Comment by ryu1kn** [comment]
Let's get this feature out with the simplest functionality. After we get feedback, we'll decide how to evolve it from there.

* Save all highlights to the most limited scope settings
* Overwrite existing highlights in settings on save
* Do not save a highlight if one is already saved in some settings
* Read highlights from the most limited scope settings
* Read highlights on extension startup

**Comment by mjunaidch** [comment]
Hello,

This is great plugin . I am waiting for Save Highlight feature. I think it comes soon... @ryu1kn 

Regards

**Comment by ryu1kn** [comment]
Thanks @mjunaidch . I started working on Dec but got distracted by other stuff. I should resume the work 😄

**Comment by ryu1kn** [comment]
Finally published as v0.11.0! 🎉

Sorry that it took me a year. @djmisterjon @Otiel  @thomasf , if you're still using TextMarker, please try it out 😉

**Comment by Otiel** [comment]
It works fine according to my few tests. At first I thought it didn't work because I didn't think I was supposed to call "Save All Highlights" before restarting VS code. Hence #10.

**Comment by ryu1kn** [comment]
Cool, thanks for testing it out @Otiel !
